### PR TITLE
Adds proper rendering for 4:3 aspect ration

### PR DESCRIPTION
**Pull request by WizzardMaker**
The current system doesn't properly render the game at the correct resolution, but rather SDL2 hard converts the resolution (also scaling the cursor)

This is rather inconvenient and also leads to inconsitencies in how the game handles input and rendering - moving away from the SDL2 implementation for scaled rendering unifyies the rendering

### CODE REVIEW

**Comment by mr-dev-cmd** [comment]
Hi,
I tested again on my Linux system and got an segmentation fault when I start it.

I have a Nvidia Grafic card that is in "on demand" mode. Means I normally use my Intel grafic adapter unless I start a game with the prefix "__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia".
When I try that with the AT application, the game starts but it is very slowly.

**Comment by WizzardMaker** [comment]
Against which SDL2 version are you building?

**Comment by mr-dev-cmd** [comment]
Actually it was even only playable in window mode. Even making that window to fullscreen made it impossible to click something. Something is wrong with the scaling.

The version of sdl2 I will check tomorrow.

**Comment by WizzardMaker** [comment]
Could you also check which renderer SDL2 chooses? The game writes that to the debug log (either console log or debug text file next to the executable)

**Comment by mr-dev-cmd** [comment]
Hi,
I added some log files:
1. debug log of the version in the develop branch.
2. debug log of this PR (Intel)
3. debug log of this PR with the Prefix that it uses the Nvidia driver
4. the output of "dpkg -l | grep sdl" to check version of sdl

It seems that I use Version 2.0.20 and I guess its too old already.
another interesting point is, that AT fall back to software presentation.

[debug_develop.txt](https://github.com/WizzardMaker/AirlineTycoon/files/10307547/debug_develop.txt)
[debug_PR_Intel.txt](https://github.com/WizzardMaker/AirlineTycoon/files/10307548/debug_PR_Intel.txt)
[debug_PR_Nvidia.txt](https://github.com/WizzardMaker/AirlineTycoon/files/10307549/debug_PR_Nvidia.txt)
[SDL_Version.txt](https://github.com/WizzardMaker/AirlineTycoon/files/10307550/SDL_Version.txt)

**Comment by WizzardMaker** [comment]
Against which architecture are you building x86 or x86_64?

Could you maybe try to build a DEBUG build (add the DEBUG define or try to build a debug release, although I don't quite know whether thats added in the CMake config) and tell me what those logs print?

**Comment by mr-dev-cmd** [comment]
I am not that professional in all that compiling things but what I can say is, that I need the :i386 development packages to compile. So I think its the x86 architecture I am building.
At the moment I install a newer SDL version.
The Debug build I will try too. If I figure out how.

**Comment by mr-dev-cmd** [comment]
here is the debug output of building the develop branch version... so its the x86_64 architecture I am building for. confusing
[debug.txt](https://github.com/WizzardMaker/AirlineTycoon/files/10307759/debug.txt)

**Comment by mr-dev-cmd** [comment]
and here the complete build output of this PR
[debug.txt](https://github.com/WizzardMaker/AirlineTycoon/files/10307789/debug.txt)

**Comment by mr-dev-cmd** [comment]
with the new SDL Version installed (2.24.0) it always fall back to software presentation. hardware acceleration seems not to work anymore on my system. Maybe I go back to the 2.0.20 that I used before.

**Comment by WizzardMaker** [comment]
Hm.. sounds like issues with SDL2 in general and not with the game - as I've not really changed any underlying rendering code in the backend

**Comment by mr-dev-cmd** [comment]
summary until now:
I could not run the version of this PR. With SDL2 v2.0.20 I even got an segmentation fault due to the attempt of running in hardware accelerated mode. (that is the mode where everything worked well before this PR)
With newer SDL2 v.2.24.0 it always falls back to software render.
Unfortunately in the software mode I always have the problem that the cursor and the screen resolution are different so I can not click anything. Only in window mode (not maximized) its playable.

**Comment by WizzardMaker** [comment]
I've removed a texture flag that maybe could cause problems on some systems - could you try again @mr-dev-cmd ?

**Comment by mr-dev-cmd** [comment]
I tested it and it seems to work now.
But there is no difference to the normal version.
Hardware accelerated works well, in software mode its not playable in fullscreen because the cursor have a different position.

In hardware accelerated mode the cursor stay small when I change to fullscreen. Don't know I you want that. It's absolutely OK for me and like before that PR.

**Pull request merged**
