### PR TITLE
Add newest fixes from @mertenpopp

### PR DESCRIPTION
**Pull request by WizzardMaker**
This is my attempt of merging all changes into the main branch

The CMake build is untested - VS works (2022)
Builds on Windows

Also adds
- increased route limit to 1500 (<-600)
- descriptive error message when adding routes with missing cities
- fixes the randomness of used planes (also increases randomness - always starts with a random plane at the start of the game - probably needs some more tweaking)

### CODE REVIEW

**Comment by mr-dev-cmd** [comment]
Hi,
when I try to compile in Linux i get the error message:

AirlineTycoon/src/TeakLibW.h:44:93: error: attributes are not allowed on a function-definition
   44 | inline void V_AT_Log_I(const std::string origin, const std::string format, va_list varargs) SDL_PRINTF_VARARG_FUNC(2)

I installed SDL2 packages for i386 on my ubuntu 22.04.
Cmake was running well, but the following "make" gave me lots of those errors above.

I don't know what I am doing wrong. Some more build instructions would be nice.

best regards! Good job so far. I love your guys work!

**Comment by WizzardMaker** [comment]
Thanks for the feedback, will take a look at it as soon as I can

**Comment by mr-dev-cmd** [comment]
I tried to compile the master branch from @mertenpopp and it worked without errors.
Unfortunately I can not start the program. It seams that it looks for the English files but I only have the German folders.
Is it possible to set a flag to German before compiling, or something?

**Comment by WizzardMaker** [comment]
Can you write the logs/errors, or rather what files are reported missing, in here?

**Comment by WizzardMaker** [comment]
I also fixed all build errors on my linux machine - will push my changes later

**Comment by mr-dev-cmd** [comment]
I am looking forward to try your new Code.

The mertenpopp Version that I was able to build, only needed some folders in the subfolder "de". Then it started. The only last problem I have, is, that the voices are not found. I must disable the voices otherwise I get a segmentation fault when talk to anybody. I don't know where voices folder must be and if I need to make everything lowercase. 

I will just try your version later. Maybe that will find the voices.

**Comment by mr-dev-cmd** [comment]
I just solved the "voices" problem for me.
In the Sound.cpp is a line 
"CString suffix = ".ogg";
I changed that to
CString suffix = ".raw";
and made all my voices raw files and folders to lowercase.

**Comment by WizzardMaker** [comment]
Yeah, found that too
There are a few changes to the linux build in regards to files

What version of ATD do you own? Steam, GoG, Retail?

**Comment by WizzardMaker** [comment]
I added some fallbacks for different folder structures/file encodings - hope that fixes all of your problems.

Casing is still a major problem on linux though, due to different game versions having different casing formats


I also added build guides to the readme, could you check if I missed some steps for linux?

**Comment by mr-dev-cmd** [comment]
Hi.
I used your Code from yesterday already and it worked well. I only made the small adjustments to have it german and to use the raw voice files.
The folder structure of my retail version I adjusted already before, so I could start and play without problems. 

I will try your recent update as soon as I can, to check if it works with the original file structure too.

**Comment by mr-dev-cmd** [comment]
For building I used the Information in the Compile.txt. For Ubuntu it's a little different. I added this here:
‐----------------
#Prerequisites
Linux x86 System (AMD64 only with MultiArch for i686)

##Fedora AMD64
sudo dnf install jansson-devel.i686 SDL2*-devel.i686

##Ubuntu x64
sudo apt-get install libjansson-dev:i386 libsdl2*-dev:i386

#Building on AMD64
mkdir build
cd build
cmake -DCMAKE_TOOLCHAIN_FILE=../Toolchain-i686.cmake ..
-----------------

**Comment by mr-dev-cmd** [comment]
The casing problem could be solved by a script that changes all the files to lowercase. That could be dangerous if used in the wrong folder, but maybe a check for the executable AT in the same folder could minimise that risk.

**Comment by mr-dev-cmd** [comment]
> > The casing problem could be solved by a script that changes all the files to lowercase. That could be dangerous if used in the wrong folder, but maybe a check for the executable AT in the same folder could minimise that risk.
> 
> I wouldn't want to supply a script, but rather give a guide on how you would fix it yourself - linux is still rather niche and those users should be capable enough to force lower casing for every file, if they know that they have to do it

Thats true

**Comment by mr-dev-cmd** [comment]
unfortunately the new Code give me build errors:

src/TeakLibW/TeakFile.cpp:232:17: error: variable ‘DoesDirectoryExist(const char*)::stat info’ has initializer but incomplete type
  232 |     struct stat info{};
...
src/TeakLibW/TeakFile.cpp:234:25: error: invalid use of incomplete type ‘struct DoesDirectoryExist(const char*)::stat’
  234 |     if (stat(path, &info) == 0 && (info.st_mode & S_IFMT) == S_IFDIR) {

**Comment by mr-dev-cmd** [comment]
Hello again,
I found some bugs, but I am not sure, if its related to my version and/or Linux.
The new features about Information from advisors (e.g. finance or spy) show me that there are more pages (1/8), but when I click to change to change to second page the game crash with a segmentation fault. Not sure if there are some files missing, or if its a bug in the code.

**Comment by WizzardMaker** [comment]
> 



> Hello again, I found some bugs, but I am not sure, if its related to my version and/or Linux. The new features about Information from advisors (e.g. finance or spy) show me that there are more pages (1/8), but when I click to change to change to second page the game crash with a segmentation fault. Not sure if there are some files missing, or if its a bug in the code.

Hm, I can't replicate the bug - my filofax works; at least on windows

**Comment by mr-dev-cmd** [comment]
> > 
> 
> > Hello again, I found some bugs, but I am not sure, if its related to my version and/or Linux. The new features about Information from advisors (e.g. finance or spy) show me that there are more pages (1/8), but when I click to change to change to second page the game crash with a segmentation fault. Not sure if there are some files missing, or if its a bug in the code.
> 
> Hm, I can't replicate the bug - my filofax works; at least on windows

I guess it is a uppercase/lowercase issue. But to confirm that I will wait for the next Windows Release and test it there.
I not really understand the c++ Code, so maybe you can tell me what files are necessary for that New filofax Featurs? Maybe my ATD version even miss some. (I dont have a title2.gli already, what is no issue until now.)

**Comment by WizzardMaker** [comment]
Could you maybe send me a save of that crashing game? I just want to rule things out

> I not really understand the c++ Code, so maybe you can tell me what files are necessary for that New filofax Featurs? Maybe my ATD version even miss some. (I dont have a title2.gli already, what is no issue until now.)

There aren't really any extra files necessary for the new features afaik.

**Comment by mr-dev-cmd** [comment]
I can build the updated code without errors again. Good job.
However I get some warnings (that I usually ignore) that can be a hint to the not working filofax information.
For me the game crash even I create a new game, so I think a savegame would not really help.
I add a file with all the warnings I got while building.
[warnings.txt](https://github.com/WizzardMaker/AirlineTycoon/files/10006920/warnings.txt)

**Comment by mr-dev-cmd** [comment]
I tested again. less warnings no errors.

I could find the reason for the game crash in filofax infos. Its related to information on the second page only. In the source code you can find it in Block.cpp line 1854. Its the "{10001, ref.KerosinVorrat}" that makes trouble. when I remove it, the game dont crash anymore. I add a savegame for quick tests.
[game0.dat.zip](https://github.com/WizzardMaker/AirlineTycoon/files/10010823/game0.dat.zip)

Another thing I can report is, that the fallback to no language prefix works now.
Unfortunately I can not test it in a real steam or gog version, but in my "self made" folder structure where I put some folders in a new subfolder "de", it dont find the files anymore. It seems that it always fall back to "no prefix". How the game actually test the folder structure and know when to use what prefix or no prefix.

**Comment by WizzardMaker** [comment]
Yeah, now I could replicate the bug - a translation string was malformed, which caused the crash

The game checks for the presence of the game's lamguage specific folder, e. g. Your game is in German, so it searches for the "de" folder.

This folder is more or less a "prefix" for all data relevant files. No prefix would be used, if the game can't find that language specific folder 

That first check should hopefully work - although only tested on Windows again

**Comment by mr-dev-cmd** [comment]
Nice.
Now that I know where those texts are standing I could find out why 2 german Umlaute did not be shown correctly.
the Lines 2287 and 2288 in the takeoff.cpp must be changed from "ü" to "\xFC" that its shown correctly in game.

The language check ignores my self-made "de" folder and always want no prefix now.

**Comment by mr-dev-cmd** [comment]
There is another bug, related to the missions.
One I already placed to the "issues" (tutorial crash).
Another one I tell you now here, but maybe its better in the issues too?
The first mission of the second campaign does not end properly. The reason can be that all competitors are out in that savegame.
[game2.dat.zip](https://github.com/WizzardMaker/AirlineTycoon/files/10015669/game2.dat.zip)

**Comment by Torston420** [comment]
`sbl.h` fails to compile on Arch-based distros with `error: 'exchange' is not a member of 'std'`
Adding `#include <utility>` fixes and allows it to compile.

**Comment by WizzardMaker** [comment]
> `sbl.h` fails to compile on Arch-based distros with `error: 'exchange' is not a member of 'std'` Adding `#include <utility>` fixes and allows it to compile.

Thanks! Will add that asap

**Comment by WizzardMaker** [comment]
> There is another bug, related to the missions. One I already placed to the "issues" (tutorial crash). Another one I tell you now here, but maybe its better in the issues too? The first mission of the second campaign does not end properly. The reason can be that all competitors are out in that savegame. [game2.dat.zip](https://github.com/WizzardMaker/AirlineTycoon/files/10015669/game2.dat.zip)

Yeah, I think this PR is reaching its limit with the relevance of these comments

This PR seems to be (except for the Arch Linux build error) more or less complete and all crashes or issues should go into dedicated github issues

Could you create an issue for the crash in that save?

**Comment by mr-dev-cmd** [comment]
> > There is another bug, related to the missions. One I already placed to the "issues" (tutorial crash). Another one I tell you now here, but maybe its better in the issues too? The first mission of the second campaign does not end properly. The reason can be that all competitors are out in that savegame. [game2.dat.zip](https://github.com/WizzardMaker/AirlineTycoon/files/10015669/game2.dat.zip)
> 
> Yeah, I think this PR is reaching its limit with the relevance of these comments
> 
> This PR seems to be (except for the Arch Linux build error) more or less complete and all crashes or issues should go into dedicated github issues
> 
> Could you create an issue for the crash in that save?

Everything works for me now. At least for my retail Version without language specific folders. When I simulated it by creating a "de" folder and moved the related files to there, it always ignored the "de" folder and did not start. But actually that could be easily solved by some folder moving, in case it's an issue for others too.
So for me it's fine. All future issues will go to the dedicated github issues.
Again, good job!

**Comment by WizzardMaker** [comment]
Newest commits fix loading of older save games (pre these changes) - this though makes this now incompatible with savegames pre this commit, post this pull request

This also fixes most of the problems with the game editor (although the editor itself is rather finicky)

**Comment by mr-dev-cmd** [comment]
The rocket prices work now, but the videos still run terribly slow for me.

**Pull request merged**
